In [2]:
import pandas as pd
sample = pd.read_pickle('E:/Data/Labor Data/sample_100k.pkl')

In [4]:
# sample[0]

In [9]:
# print(type(sample[0]))
sample[0].keys()

dict_keys(['publications', 'awards', 'languages', 'memberships', 'certifications', 'patents', 'experiences', 'educations', 'resume', 'tags', 'resumeUpdatedDt', 'lastUpdateDt', 'currentIndustry', 'priorIndustries', 'downloadsLeft', 'searchesLeft', 'resetDt', 'error', 'firstName', 'lastName', 'uniqueId', 'title', 'location', 'expertise', 'profileUrl', 'pictureUrl', 'summary', 'profileSSOUrl', 'emails', 'phoneNumbers', 'externalProfiles'])

In [12]:
sample[0]['experiences'][1]['title']

'Senior Director Product Strategy and Product Partnerships'

In [13]:
x= 'luke, i am your father'

In [14]:
x

'luke, i am your father'

In [15]:
x.title()

'Luke, I Am Your Father'

In [16]:
x = 'How many characters and words are in this string?'

In [17]:
x

'How many characters and words are in this string?'

In [25]:
len(x)
x.count(' ')
len(x.split())-1
len(x.replace(' ',''))

41

In [19]:
x.rsplit()

['How', 'many', 'characters', 'and', 'words', 'are', 'in', 'this', 'string?']

In [20]:
x.split()

['How', 'many', 'characters', 'and', 'words', 'are', 'in', 'this', 'string?']

In [27]:
len(x.split())

9

In [30]:
y = x+' ????'

In [31]:
y.split()

['How',
 'many',
 'characters',
 'and',
 'words',
 'are',
 'in',
 'this',
 'string?',
 '????']

In [32]:
list(x)

['H',
 'o',
 'w',
 ' ',
 'm',
 'a',
 'n',
 'y',
 ' ',
 'c',
 'h',
 'a',
 'r',
 'a',
 'c',
 't',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'w',
 'o',
 'r',
 'd',
 's',
 ' ',
 'a',
 'r',
 'e',
 ' ',
 'i',
 'n',
 ' ',
 't',
 'h',
 'i',
 's',
 ' ',
 's',
 't',
 'r',
 'i',
 'n',
 'g',
 '?']

In [33]:
[i for i in x]

['H',
 'o',
 'w',
 ' ',
 'm',
 'a',
 'n',
 'y',
 ' ',
 'c',
 'h',
 'a',
 'r',
 'a',
 'c',
 't',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'w',
 'o',
 'r',
 'd',
 's',
 ' ',
 'a',
 'r',
 'e',
 ' ',
 'i',
 'n',
 ' ',
 't',
 'h',
 'i',
 's',
 ' ',
 's',
 't',
 'r',
 'i',
 'n',
 'g',
 '?']

In [35]:
x = [1, 2, 3]
y = 'bootcamp'
z = x + [y]

In [36]:
z

[1, 2, 3, 'bootcamp']

In [40]:
# "".join(i for i in x)
x2 = ''
for i in x:
    x2+=str(i)

In [41]:
x2+y

'123bootcamp'

In [42]:
x = [1, 2, 3, 4, 5]

In [43]:
x[0]

1

In [44]:
x[-1]

5

In [45]:
x[:-1]

[1, 2, 3, 4]

In [46]:
sentence = 'This is a sentence; please slice it.'

In [49]:
sentence[5:7]

'is'

In [51]:
# for string in sentence:
#     print(string)

In [53]:
x= [1, 2, "a", 'b', "fast", 'slow', 3, "Raghu", 'Liuren', 10]

In [54]:
x

[1, 2, 'a', 'b', 'fast', 'slow', 3, 'Raghu', 'Liuren', 10]

In [55]:
for i in x:
    print(i)

1
2
a
b
fast
slow
3
Raghu
Liuren
10


In [57]:
for i in range(len(x)):
    print(x[i])

1
2
a
b
fast
slow
3
Raghu
Liuren
10


In [59]:
for i in x:
    if type(i)==str:
        print(i)

a
b
fast
slow
Raghu
Liuren


In [60]:
5 == 5.0

True

In [61]:
5 is 5.0

False

In [62]:
def angle(H,M):
    total_mins = H*60 + M
    hour_angle = total_mins*.5
    minute_angle = M*6
    angle= hour_angle-minute_angle
    if angle<0:
        angle = 360 + angle
    if angle>180:
        angle = 360 - angle
    if angle==360:
        angle = 0
    return angle

In [71]:
angle2(6,42)

51.0

In [72]:
angle2(12,55)

57.5

In [73]:
angle2(6,30)

15.0

In [74]:
angle2(12,30)

165.0

In [70]:
def angle2(H,M):
    return 180 - abs(180 - abs(30*H - 5.5*M))

In [75]:
import numpy as np

In [84]:
a = [i**.5 for i in range(1000000)]
b = [i*4 for i in range(1000000)]

In [89]:
%%time
c = []
# csum = 0
for i in range(1000000):
    c.append(a[i]*b[i])
#     csum += a[i]*b[i]

Wall time: 273 ms


In [86]:
a_array = np.array(a)
b_array = np.array(b)

In [93]:
a_array

array([  0.        ,   1.        ,   1.41421356, ..., 999.9985    ,
       999.999     , 999.9995    ])

In [97]:
a_array.shape

(1000000,)

In [98]:
c_array = np.array([[1,2,3],[4,5,6]])

In [99]:
c_array

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
c_array.shape

(2, 3)

In [94]:
type(a_array)

numpy.ndarray

In [87]:
%%time
sum(a_array*b_array)

Wall time: 159 ms


1599998000000415.5

In [88]:
csum

1599998000000415.5

In [90]:
c

[0.0,
 4.0,
 11.313708498984761,
 20.784609690826528,
 32.0,
 44.721359549995796,
 58.78775382679627,
 74.08103670980854,
 90.50966799187809,
 108.0,
 126.49110640673518,
 145.9314907756376,
 166.27687752661222,
 187.48866632412742,
 209.53281365934072,
 232.379000772445,
 256.0,
 280.3711825420009,
 305.4701294725885,
 331.27631970909124,
 357.77087639996637,
 384.93635837629057,
 412.75658686446184,
 441.2165001447702,
 470.30203061437015,
 500.0,
 530.2980294136496,
 561.1844616523163,
 592.6482936784683,
 624.6791176276024,
 657.2670690061993,
 690.4027809909227,
 724.0773439350247,
 758.2822693430198,
 793.0094576989609,
 828.2511696339462,
 864.0,
 900.2488544841365,
 936.9909284512844,
 974.2196877501501,
 1011.9288512538815,
 1050.1123749389872,
 1088.7644373325206,
 1127.879426179944,
 1167.4519262051008,
 1207.4767078498865,
 1247.9487168950493,
 1288.8630648753963,
 1330.2150202128978,
 1372.0,
 1414.213562373095,
 1456.8513994227415,
 1499.9093305930194,
 1543.3832965274698

In [91]:
%%time
a_array*b_array

Wall time: 5 ms


array([0.00000000e+00, 4.00000000e+00, 1.13137085e+01, ...,
       3.99998200e+09, 3.99998800e+09, 3.99999400e+09])

In [103]:
a_array

array([  0.        ,   1.        ,   1.41421356, ..., 999.9985    ,
       999.999     , 999.9995    ])

In [106]:
np.sqrt(a_array)

array([ 0.        ,  1.        ,  1.18920712, ..., 31.62275288,
       31.62276079, 31.6227687 ])

In [107]:
import pandas as pd

In [173]:
df = pd.DataFrame({"GDP": [5974.7, 10031.0, 14681.1],
                   "CPI": [127.5, 169.3, 217.488],
                   "Year": [1990, 2000, 2010],
                   "Country": ["US", "US", "US"]})

In [174]:
type(df)

pandas.core.frame.DataFrame

In [175]:
df

GDP      CPI  Year Country
0   5974.7  127.500  1990      US
1  10031.0  169.300  2000      US
2  14681.1  217.488  2010      US

In [176]:
df.shape

(3, 4)

In [177]:
df['GDP']

0     5974.7
1    10031.0
2    14681.1
Name: GDP, dtype: float64

In [178]:
type(df['GDP'])

pandas.core.series.Series

In [179]:
dict(df['GDP'])

{0: 5974.7, 1: 10031.0, 2: 14681.1}

In [180]:
df

GDP      CPI  Year Country
0   5974.7  127.500  1990      US
1  10031.0  169.300  2000      US
2  14681.1  217.488  2010      US

In [181]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [182]:
df.columns

Index(['GDP', 'CPI', 'Year', 'Country'], dtype='object')

In [183]:
df.dtypes

GDP        float64
CPI        float64
Year         int64
Country     object
dtype: object

In [184]:
df

GDP      CPI  Year Country
0   5974.7  127.500  1990      US
1  10031.0  169.300  2000      US
2  14681.1  217.488  2010      US

In [185]:
df.mean()

GDP     10228.933333
CPI       171.429333
Year     2000.000000
dtype: float64

In [186]:
df.mean(1)

0    2697.400000
1    4066.766667
2    5636.196000
dtype: float64

In [187]:
df.T

0      1        2
GDP      5974.7  10031  14681.1
CPI       127.5  169.3  217.488
Year       1990   2000     2010
Country      US     US       US

In [188]:
df.rename(columns={'GDP':'nominal_gdp'})

nominal_gdp      CPI  Year Country
0       5974.7  127.500  1990      US
1      10031.0  169.300  2000      US
2      14681.1  217.488  2010      US

In [189]:
df = df.rename(columns={'GDP':'nominal_gdp'})

In [190]:
df['real_gdp'] = df['nominal_gdp']*(100/df['CPI'])

In [191]:
df

nominal_gdp      CPI  Year Country     real_gdp
0       5974.7  127.500  1990      US  4686.039216
1      10031.0  169.300  2000      US  5924.985233
2      14681.1  217.488  2010      US  6750.303465

In [192]:
df = df.drop('Country',axis=1)

In [193]:
df

nominal_gdp      CPI  Year     real_gdp
0       5974.7  127.500  1990  4686.039216
1      10031.0  169.300  2000  5924.985233
2      14681.1  217.488  2010  6750.303465

In [194]:
df.set_index('Year',inplace=True)

In [195]:
df

nominal_gdp      CPI     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [196]:
df.shape

(3, 3)

In [197]:
df.reset_index().reset_index().reset_index()#.shape

level_0  index  Year  nominal_gdp      CPI     real_gdp
0        0      0  1990       5974.7  127.500  4686.039216
1        1      1  2000      10031.0  169.300  5924.985233
2        2      2  2010      14681.1  217.488  6750.303465

In [198]:
df.shape

(3, 3)

In [199]:
df

nominal_gdp      CPI     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [200]:
df[['nominal_gdp','real_gdp']]

nominal_gdp     real_gdp
Year                          
1990       5974.7  4686.039216
2000      10031.0  5924.985233
2010      14681.1  6750.303465

In [201]:
df.mean()

nominal_gdp    10228.933333
CPI              171.429333
real_gdp        5787.109305
dtype: float64

In [202]:
df.std()

nominal_gdp    4356.573590
CPI              45.031773
real_gdp       1039.015905
dtype: float64

In [203]:
df.median()

nominal_gdp    10031.000000
CPI              169.300000
real_gdp        5924.985233
dtype: float64

In [204]:
df.corr()

nominal_gdp       CPI  real_gdp
nominal_gdp     1.000000  0.999999  0.988084
CPI             0.999999  1.000000  0.987835
real_gdp        0.988084  0.987835  1.000000

In [205]:
df.describe()

nominal_gdp         CPI     real_gdp
count      3.000000    3.000000     3.000000
mean   10228.933333  171.429333  5787.109305
std     4356.573590   45.031773  1039.015905
min     5974.700000  127.500000  4686.039216
25%     8002.850000  148.400000  5305.512224
50%    10031.000000  169.300000  5924.985233
75%    12356.050000  193.394000  6337.644349
max    14681.100000  217.488000  6750.303465

In [206]:
df

nominal_gdp      CPI     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [207]:
df.index

Int64Index([1990, 2000, 2010], dtype='int64', name='Year')

In [208]:
df['nominal_gdp'][2000]

10031.0

In [209]:
for i in df.index:
    print(i,df['nominal_gdp'][i] - df['real_gdp'][i])

1990 1288.6607843137253
2000 4106.014766686356
2010 7930.79653498124


In [210]:
df['nominal_gdp'] - df['real_gdp']

Year
1990    1288.660784
2000    4106.014767
2010    7930.796535
dtype: float64

In [211]:
df

nominal_gdp      CPI     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [212]:
df.columns

Index(['nominal_gdp', 'CPI', 'real_gdp'], dtype='object')

In [213]:
# df.columns.capitalize()

AttributeError: 'Index' object has no attribute 'capitalize'

In [224]:
for i in df.columns:
    df = df.rename(columns={i:i.upper()})

In [225]:
df

NOMINAL_GDP      CPI     REAL_GDP
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [226]:
[i.lower() for i in df.columns]

['nominal_gdp', 'cpi', 'real_gdp']

In [227]:
df.columns = [i.lower() for i in df.columns]

In [228]:
df

nominal_gdp      cpi     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [229]:
df.to_excel('sample_file.xlsx')

In [230]:
df.to_csv('sample_file.csv')

In [231]:
df2 = pd.read_csv('sample_file.csv')

In [232]:
df2

Year  nominal_gdp      cpi     real_gdp
0  1990       5974.7  127.500  4686.039216
1  2000      10031.0  169.300  5924.985233
2  2010      14681.1  217.488  6750.303465

In [233]:
df.to_pickle('sample_file.pkl')

In [234]:
df3 = pd.read_pickle('sample_file.pkl')

In [235]:
df3

nominal_gdp      cpi     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [236]:
df4 = pd.read_pickle('C:/Users/bzweig/Desktop/sample_file.pkl')

In [237]:
df4

nominal_gdp      cpi     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [238]:
df

nominal_gdp      cpi     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2000      10031.0  169.300  5924.985233
2010      14681.1  217.488  6750.303465

In [245]:
df.iloc[1:,:-1]

nominal_gdp      cpi
Year                      
2000      10031.0  169.300
2010      14681.1  217.488

In [246]:
df.loc[2000:,:'cpi']

nominal_gdp      cpi
Year                      
2000      10031.0  169.300
2010      14681.1  217.488

In [249]:
df.loc[2000:,:].mean()

nominal_gdp    12356.050000
cpi              193.394000
real_gdp        6337.644349
dtype: float64

In [251]:
df2 = df.sample(frac=1)

In [255]:
df2.loc[1990:]

nominal_gdp      cpi     real_gdp
Year                                   
1990       5974.7  127.500  4686.039216
2010      14681.1  217.488  6750.303465